elCicdTemplates:
- templateName: chart.yaml
  version: $<VERSION>
  type: application
  dependencies:
  - name: elCicdRenderer
    version: 0.1.0
    repository: elCicdCharts/elCicdRenderer
  - name: elCicdKubernetes
    version: 0.1.0
    repository: elCicdCharts/elCicdKubernetes
  - name: elCicdCommon
    version: 0.1.0
    repository: elCicdCharts/elCicdCommon