elCicdTemplates:
- templateName: chart-yaml
  version: $<VERSION>
  type: application

  dependencies:
  - name: elCicdRenderer
    version: 0.1.0
    repository: $<HELM_REPOSITORY_URL>
  - name: elCicdKubernetes
    version: 0.1.0
    repository: $<HELM_REPOSITORY_URL>
  - name: elCicdCommon
    version: 0.1.0
    repository: $<HELM_REPOSITORY_URL>