#!/bin/bash
#!/bin/bash
set -e

PRE_KUST_HELM_FILE=${4}
POST_KUST_HELM_FILE=${5}

cd ${EL_CICD_KUSTOMIZE_DIR}

cat <&0 > ${EL_CICD_BASE_KUSTOMIZE_DIR}/${EL_CICD_PRE_KUST_HELM_FILE}
(cd ${EL_CICD_BASE_KUSTOMIZE_DIR} && kustomize edit add resource ${EL_CICD_PRE_KUST_HELM_FILE})

kustomize build ${EL_CICD_KUSTOMIZE_DIR} > ${EL_CICD_POST_KUST_HELM_FILE}

cat ${EL_CICD_POST_KUST_HELM_FILE}

set +e