elCicdTemplates:
- templateName: values-yaml
  valuesYaml:
    elCicdTemplates:
    - templateName: copyResource
      objName: elcicd-\$<PROD_ENV>-registry-credentials
      kind: Secret
      fromNamespace: $<EL_CICD_MASTER_NAMESPACE>
      toNamespace: \$<HELM_RELEASE_NAMESPACE>
