#!/usr/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later

set -E

trap 'ERRO_LINENO=$LINENO' ERR
trap '_failure' EXIT

_failure() {
   ERR_CODE=$?
   set +xv
   if [[  $- =~ e && ${ERR_CODE} != 0 ]] 
   then
       echo
       echo "========= CATASTROPHIC COMMAND FAIL ========="
       echo
       echo "el-CICD EXITED ON ERROR CODE: ${ERR_CODE}"
       echo
       LEN=${#BASH_LINENO[@]}
       for (( INDEX=0; INDEX<$LEN-1; INDEX++ ))
       do
           echo '---'
           echo "FILE: $(basename ${BASH_SOURCE[${INDEX}+1]})"
           echo "  FUNCTION: ${FUNCNAME[${INDEX}+1]}"
           if [[ ${INDEX} > 0 ]]
           then
               echo "  COMMAND: ${FUNCNAME[${INDEX}]}"
               echo "  LINE: ${BASH_LINENO[${INDEX}]}"
           else
               echo "  COMMAND: ${BASH_COMMAND}"
               echo "  LINE: ${ERRO_LINENO}"
           fi
       done
       echo
       echo "======= END CATASTROPHIC COMMAND FAIL ======="
       echo
   fi
}

cd "$(dirname ${0})"

read -r -d '' WARNING_MSG << EOM
===================================================================
WARNING:
SUDO AND CLUSTER ADMIN PRIVILEGES REQUIRED WHEN USING THIS UTILITY

ACCESS TO el-CICD ONBOARDING AUTOMATION SERVERS SHOULD BE RESTRICTED TO CLUSTER ADMINS
===================================================================
EOM

read -r -d '' HELP_MSG << EOM
Usage: oc el-cicd-adm [OPTION] [root-config-file]

el-CICD Admin Utility

Options:
    -N,   --non-prod:        bootstraps Non-prod el-CICD Onboarding Automation Server
    -n,   --non-prod-creds:  refresh Non-prod el-CICD Onboarding Automation Server credentials
    -P,   --prod:            bootstraps Prod el-CICD Onboarding Automation Server
    -p,   --prod-creds:      refresh Prod el-CICD Onboarding Automation Server credentials
    -c,   --cicd-creds:      run the refresh-credentials pipeline
    -s,   --sealed-secrets:  reinstall/upgrade Sealed Secrets
    -j,   --jenkins:         only build el-CICD Jenkins image
    -a,   --agents:          only build el-CICD Jenkins agent images
    -A,   --jenkins-agents:  build el-CICD Jenkins and Jenkins agent images
    -D,   --setup-dev:       setup an environment for developing el-CICD
          --start-crc:       start OpenShift Local development cluster
    -T,   --tear-down-dev:   tear down an environment for developing el-CICD
          --help:            display this help text and exit

root-config-file:
    file name or path to a root configuration file relative the root of the el-CICD-config directory
EOM

read -r -d '' DEV_SETUP_WELCOME_MSG << EOM
Welcome to the el-CICD setup utility for developing with or on el-CICD.

el-CICD will perform the necessary setup for running the tutorial or developing with el-CICD:
  - Optionally setup OpenShift Local, if downloaded to the el-CICD home directory and not currently installed.
  - Optionally setup up an image registry to mimic an external registry, with or without an NFS share.
  - Clone and push all el-CICD and sample project Git repositories into your Git host (only GitHub is supported currently).
  - Install the Sealed Secrets controller onto your cluster

NOTES: Red Hat OpenShift Local may be downloaded from here:
       https://developers.redhat.com/products/openshift-local/overview
EOM

read -r -d '' DEV_TEAR_DOWN_WELCOME_MSG << EOM
Welcome to the el-CICD dev environment tear down utility.
Before beginning to tear down your environment, please make sure of the following:

1) Log into an OKD cluster as cluster admin, or you can use Red Hat OpenShift Local:
   https://developers.redhat.com/products/openshift-local/overview
   NOTE: el-CICD can setup OpenShift Local for you if requested.

2) Have root priveleges on this machine. sudo password is required to complete setup.

el-CICD will optionally tear down:
    - OpenShift Local
    - The cluster image registry
    - The NFS registry directory
    - Remove el-CICD repositories pushed to your Git host
EOM

_BOLD=$(tput bold)
_REGULAR=$(tput sgr0)

set -o allexport

BOOTSTRAP_DIR=$(pwd)

EL_CICD_HOME=$(dirname ${BOOTSTRAP_DIR})

CLI_OPTION=${1}

ROOT_CONFIG_FILE=${2}

CONFIG_DIR=${BOOTSTRAP_DIR}/../el-CICD-config

case "${CLI_OPTION}" in
    '')
         echo "Usage: oc el-cicd-adm [OPTION] [root-config-file]"
         echo "Try 'el-cicd-adm --help' for more information."
         exit 1
    ;;

    '--help')
        echo "${HELP_MSG}"
        exit 0
    ;;
esac

SERVER_TYPE_PROD=prod
SERVER_TYPE_NON_PROD=non-prod

echo "${WARNING_MSG}"
sleep 2

SCRIPTS_DIR=${BOOTSTRAP_DIR}/scripts
SCRIPTS_RESOURCES_DIR=${SCRIPTS_DIR}/resources
SYSTEM_DEFAULT_CONFIG_FILE=${SCRIPTS_RESOURCES_DIR}/system-default.conf

RESOURCES_DIR=${BOOTSTRAP_DIR}/resources
PIPELINES_DIR=${RESOURCES_DIR}/pipelines
TEMPLATES_DIR=${RESOURCES_DIR}/templates
HELM_DIR=${BOOTSTRAP_DIR}/.helm

NON_PROD_ONBOARDING_PIPELINES_DIR=${PIPELINES_DIR}/non-prod-onboarding
NON_PROD_AUTOMATION_PIPELINES_DIR=${PIPELINES_DIR}/non-prod-automation

PROD_ONBOARDING_PIPELINES_DIR=${PIPELINES_DIR}/prod-onboarding
PROD_AUTOMATION_PIPELINES_DIR=${PIPELINES_DIR}/prod-automation

CONFIG_HELM_DIR=${CONFIG_DIR}/.helm
CONFIG_BOOTSTRAP_DIR=${CONFIG_DIR}/bootstrap
CONFIG_JENKINS_DIR=${CONFIG_DIR}/jenkins

TARGET_JENKINS_BUILD_DIR=${BOOTSTRAP_DIR}/../jenkins-target

echo
echo 'Loading el-CICD environment...'

set -e
echo
for FILE in $(ls ${SCRIPTS_DIR}/*.sh | xargs -n 1 basename)
do
    echo "Sourcing file: ${FILE}"
    source "${SCRIPTS_DIR}/${FILE}"
done

source ${CONFIG_DIR}/${ROOT_CONFIG_FILE}
_create_meta_info_file ${INCLUDE_BOOTSTRAP_FILES}
source ${META_INFO_FILE}
set +e

echo
echo 'el-CICD environment loaded'

set +o allexport

if [[ ! -z $(command -v crc) ]]
then
    CRC_EXEC=$(which crc)
    CLUSTER_API_HOSTNAME=$(oc whoami --show-server | awk -F '://' '{ print $2 }')
elif [[ -z $(which oc --skip-alias 2>/dev/null) ]]
then
    echo
    echo '============ WARNING!!! =============='
    echo
    echo 'IF NOT INSTALLING OPENSHIFT LOCAL, YOU MUST INSTALL THE OKD CLI!'
    echo 
    echo '============ WARNING!!! =============='
fi

_verify_scm_secret_files_exist

echo
case ${CLI_OPTION} in

    '--non-prod' | '-N')
        echo "BOOTSTRAPPING NON-PROD"
        
        _bootstrap_el_cicd ${SERVER_TYPE_NON_PROD}
    ;;

    '--prod' | '-P')
        echo "BOOTSTRAPPING PROD"
        
        _bootstrap_el_cicd ${SERVER_TYPE_PROD}
    ;;

    '--non-prod-creds' | '-n')
        echo "REFRESH NON-PROD CREDENTIALS"

        _create_el_cicd_meta_info_config_map

        _refresh_non_prod_credentials
    ;;

    '--prod-creds' | '-p')
        echo "REFRESH PROD CREDENTIALS"

        _create_el_cicd_meta_info_config_map

        _refresh_prod_credentials
    ;;

    '--cicd-creds' | '-c')
        echo "REFRESH ALL CICD SERVERS CREDENTIALS"

        echo
        echo "Refreshing all CICD Servers in the cluster managed by ${ONBOARDING_MASTER_NAMESPACE}"
        oc start-build refresh-credentials --wait --follow -n ${ONBOARDING_MASTER_NAMESPACE}
    ;;

    '--sealed-secrets' | '-s')
        echo "INSTALL SEALED SECRETS"
        _check_sealed_secrets

        if [[ ${INSTALL_KUBESEAL} == ${_YES} ]]
        then
            _install_sealed_secrets
        fi
    ;;

    '--jenkins' | '-j')
        echo "BUILD JENKINS IMAGE"
        _build_el_cicd_jenkins_image
    ;;

    '--agents' | '-a')
        echo "BUILD JENKINS AGENT IMAGES"
        _build_el_cicd_jenkins_agent_images_image
    ;;

    '--jenkins-agents' | '-A')
        echo "UPDATE JENKINS IMAGE AND BUILD JENKINS AGENT IMAGES"
        _build_el_cicd_jenkins_image

        _build_el_cicd_jenkins_agent_images_image
    ;;

    '--setup-dev' | '-D')
        echo "BOOTSTRAPPING EL-CICD DEVELOPMENT ENVIRONMENT"

        __bootstrap_dev_environment
    ;;

    '--start-crc')
        echo "STARTING EL-CICD DEVELOPMENT ENVIRONMENT"

        _start_crc
    ;;

    '--tear-down-dev' | '-T')
        echo "TEARING DOWN EL-CICD DEVELOPMENT ENVIRONMENT"

        __tear_down_dev_environment
    ;;

    *)
        echo "ERROR: Unknown command option '${CLI_OPTION}'"
        echo
        echo "${HELP_MSG}"
        exit 1
    ;;
esac
