# SPDX-License-Identifier: LGPL-2.1-or-later

kind: Template
apiVersion: v1
metadata:
  name: create-all-jenkins-agents-template
parameters:
- name: EL_CICD_META_INFO_NAME
  description: Name oc config map holding el-CICD meta-info
  displayName: EL_CICD_META_INFO_NAME
  required: true
- name: PIPELINE_TEMPLATE_NAME
  description: Pipeline Template Name
  displayName: PIPELINE_TEMPLATE_NAME
  required: true
  value: create-all-jenkins-agents
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: create-all-jenkins-agents
  spec:
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node('master') {
              def cicdMetaData = (readJSON(text: sh(returnStdout: true, script: "oc get cm ${EL_CICD_META_INFO_NAME} -o json")))

              def scmMap = [$class: 'GitSCMSource',
                            remote: cicdMetaData.data.EL_CICD_GIT_REPO,
                            credentialsId: cicdMetaData.data.EL_CICD_READ_ONLY_GITHUB_PRIVATE_KEY_ID]
              library identifier: "el-CICD@${cicdMetaData.data.EL_CICD_BRANCH_NAME}", retriever: modernSCM(scmMap)

              cicdMetaData.data.PIPELINE_TEMPLATE_NAME = '${PIPELINE_TEMPLATE_NAME}'
              el.initMetaData(cicdMetaData.data)
          }

          node('maven') {
              createAllJenkinsAgents
          }
