# SPDX-License-Identifier: LGPL-2.1-or-later

kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: delete-project-template
parameters:
- name: EL_CICD_META_INFO_NAME
  description: Name oc config map holding el-CICD meta-info
  displayName: EL_CICD_META_INFO_NAME
  required: true
- name: PIPELINE_TEMPLATE_NAME
  description: Pipeline Template Name
  displayName: PIPELINE_TEMPLATE_NAME
  required: true
  value: delete-project-template
- name: IS_NON_PROD
  description: Is this for a Non-prod Onboarding Automation Server
  displayName: IS_NON_PROD
  required: true
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: ${PIPELINE_TEMPLATE_NAME}
  spec:
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: PROJECT_ID
            description: Project ID from auto-tracker, representing all microservices for a project
          - name: DELETE_RBAC_GROUP_JENKINS
            description: If true, non-prod environment(s) will be destroyed and rebuilt from scratch
            value: "false"
        jenkinsfile: |-
          properties([
              parameters(
                  [
                      string(name: 'PROJECT_ID', description: 'Project ID', trim: true),
                      booleanParam(name: 'DELETE_RBAC_GROUP_JENKINS', defaultValue: false, description: 'Should the RBAC group Jenkins be deleted, too?')
                  ]
              )
          ])

          node('master') {
              def cicdMetaData = (readJSON(text: sh(returnStdout: true, script: "oc get cm ${EL_CICD_META_INFO_NAME} -o json")))

              def scmMap = [$class: 'GitSCMSource',
                            remote: cicdMetaData.data.EL_CICD_GIT_REPO,
                            credentialsId: cicdMetaData.data.EL_CICD_READ_ONLY_GITHUB_PRIVATE_KEY_ID]
              library identifier: "el-CICD@${cicdMetaData.data.EL_CICD_BRANCH_NAME}", retriever: modernSCM(scmMap)

              el.initMetaData(cicdMetaData.data)
          }

          def args = [agent: el.cicd.JENKINS_AGENT_DEFAULT,
                      pipelineTemplateName: '${PIPELINE_TEMPLATE_NAME}',
                      projectId: params.PROJECT_ID,
                      deleteRbacGroupJenkins: params.DELETE_RBAC_GROUP_JENKINS?.toString() == 'true',
                      isNonProd: ${IS_NON_PROD}]
          el.node(args)
          {
              projectDeletion(args)
          }