# SPDX-License-Identifier: LGPL-2.1-or-later

kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: refresh-credentials-template
parameters:
- name: EL_CICD_META_INFO_NAME
  description: Name oc config map holding el-CICD meta-info
  displayName: EL_CICD_META_INFO_NAME
  required: true
- name: PIPELINE_TEMPLATE_NAME
  description: Pipeline Template Name
  displayName: PIPELINE_TEMPLATE_NAME
  required: true
  value: refresh-credentials
- name: IS_NON_PROD
  description: Is this for a Non-prod Onboarding Automation Server
  displayName: IS_NON_PROD
  required: true
  value: refresh-credentials
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: ${PIPELINE_TEMPLATE_NAME}
  spec:
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node('master') {
              def cicdMetaData = (readJSON(text: sh(returnStdout: true, script: "oc get cm ${EL_CICD_META_INFO_NAME} -o json")))

              def scmMap = [$class: 'GitSCMSource',
                            remote: cicdMetaData.data.EL_CICD_GIT_REPO,
                            credentialsId: cicdMetaData.data.EL_CICD_READ_ONLY_GITHUB_PRIVATE_KEY_ID]
              library identifier: "el-CICD@${cicdMetaData.data.EL_CICD_BRANCH_NAME}", retriever: modernSCM(scmMap)

              el.initMetaData(cicdMetaData.data)
          }

          def args = [agent: el.cicd.JENKINS_AGENT_DEFAULT,
                      pipelineTemplateName: '${PIPELINE_TEMPLATE_NAME}',
                      isNonProd: ${IS_NON_PROD}]
          el.node(args)
          {
              refreshCredentials(args)
          }
