{{- $_ := set . "UNDEFINED" "undefined" -}}

kind: ConfigMap
apiVersion: v1
{{ $appName := printf "%s-%s-meta-info" $.Values.projectid $.Values.microService }}
{{ $metaInfoDict := (dict "appName" $appName }}
{{ include "elCicdChart.apiMetadata" $metaInfoDict }}
data:
  projectid: {{ $.Values.projectid }}
  microservice: {{ $.Values.microService }}
  git-repo: {{ $.Values.gitRepoName }}
  src-commit-hash: {{ $.Values.srcCommitHash }}
  deployment-branch: {{ $.Values.deploymentBranch | default $.Values.UNDEFINED }}
  deployment-commit-hash: {{ $.Values.deploymentCommitHash }}
  release-version: {{ $.Values.releaseVersionTag  | default $.Values.UNDEFINED }}
  release-region: {{ $.Values.releaseRegion  | default $.Values.UNDEFINED }}
  build-number: {{ $.Values.buildNumber }}
  deploy-time: {{ $.Release.time }}
  profiles: {{ '{{ join "," $.Values.profiles }}'