apiVersion: v1
kind: PersistentVolume
metadata:
  name: %DEMO_IMAGE_REGISTRY%-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/%DEMO_IMAGE_REGISTRY%
    server: 192.168.1.70
  claimRef:
    name: %DEMO_IMAGE_REGISTRY%-pvc
  readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: %DEMO_IMAGE_REGISTRY%-pvc
  labels:
    app: %DEMO_IMAGE_REGISTRY%
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi