apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-volume
  labels:
    type: docker-registry
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/docker-registry
    server: %LOCAL_NFS_IP%
  readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  labels:
    type: docker-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: docker-registry-volume
  storageClassName: ""