elCicdTemplates-common-cicd:
- templateName: secret
  objNames: $<GIT_REPO_SSH_KEY_MODULE_IDS>
  labels:
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  stringData:
    username: "$<OBJ_NAME>"
    privateKey: |-
      $<GIT_REPO_SSH_KEY>
