elCicdDefs-prod:
  PIPELINE_DISPLAY_NAME: $<BASE_OBJ_NAME>
  EL_CICD_API_ARGS: |-
    agent: el.cicd.JENKINS_AGENT_DEFAULT,
    teamId: '$<USER_GROUP>',
    projectId: params.PROJECT_ID,
    $<EXTRA_PIPELINE_ARGS>
  PROJECT_ID_PIPELINE_PARAM: stringParam('PROJECT_ID', null, "Name of project")
    
elCicdDefs-promote-project-to-prod:
  PIPELINE_DESCRIPTION: 'Promote a release candidate to full release'
  EL_CICD_API_METHOD: promoteProjectToProd
  EXTRA_PIPELINE_ARGS: |-
    releaseVersion: params.RELEASE_VERSION
  PIPELINE_PARAMS: |-
    parameters {
      $<PROJECT_ID_PIPELINE_PARAM>
      stringParam('RELEASE_VERSION', "0.1.0", "Release Version, must be a valid Semver (https://semver.org/)")
    }
                
elCicdDefs-deploy-project-to-prod:
  PIPELINE_DESCRIPTION: 'Deploy to production environment'
  EL_CICD_API_METHOD: deployProjectToProd
  EXTRA_PIPELINE_ARGS: |-
    profile: params.PROFILE
  PIPELINE_PARAMS: |-
    parameters {
      $<PROJECT_ID_PIPELINE_PARAM>
    }

elCicdTemplates-prod:
- templateName: configMap
  objNames:
  - deploy-project-to-prod
  - promote-project-to-prod
  mustHaveEveryProfile:
  - prod
  labels:
    teamId: $<TEAM_ID>
    jenkins-pipeline: 'true'
  data: $<TEAM_PIPELINE_CONFIG_MAP_DATA>