elCicdDefs-prod:
  PIPELINE_NAME: ${BASE_OBJ_NAME}
  EL_CICD_API_ARGS: |-
    agent: el.cicd.JENKINS_AGENT_DEFAULT,
    teamId: '${USER_GROUP}',
    projectId: params.PROJECT_ID,
    versionTag: params.VERSION_TAG,
    ${EXTRA_PIPELINE_ARGS}
  PROD_PIPELINE_PARAMS: |-
    stringParam('PROJECT_ID', null, "Name of project")
    stringParam('VERSION_TAG', null, "Version")
    
elCicdDefs-promote-project-to-prod:
  PIPELINE_DESCRIPTION: 'Promote a release candidate to full release'
  EL_CICD_API_METHOD: promoteProjectToProd
  PIPELINE_PARAMS: |-
    parameters {
      ${PROD_PIPELINE_PARAMS}
    }
                
elCicdDefs-deploy-project-to-prod:
  PIPELINE_DESCRIPTION: 'Deploy to production environment'
  EL_CICD_API_METHOD: deployProjectToProd
  EXTRA_PIPELINE_ARGS: |-
    variant: params.VARIANT
  PIPELINE_PARAMS: |-
    parameters {
      ${PROD_PIPELINE_PARAMS}
      stringParam('VARIANT', null, "Variant of version to deploy; e.g. 'east', 'west', 'french', 'english', or 'pre'")
    }

elCicdTemplates-prod:
- templateName: configMap
  objNames:
  - deploy-project-to-prod
  - promote-project-to-prod
  mustHaveEveryProfile:
  - prod
  labels:
    teamId: ${TEAM_ID}
    jenkins-pipeline: 'true'
    jenkins-shared-pipeline: 'true'
  data: ${TEAM_PIPELINE_CONFIG_MAP_DATA}