elCicdDefs-nonprod:
  MODULE_PIPELINE_LABELS:
    teamId: $<TEAM_ID>
    projectid: $<PROJECT_ID>
    module: $<BASE_OBJ_NAME>
    jenkins-pipeline: 'true'
  BUILD_MODULE_ARGS: |-
    agent:  '$<CODE_BASE>',
    teamId: '$<TEAM_ID>',
    projectId: '$<PROJECT_ID>',
    gitBranch: params.GIT_BRANCH,
    moduleName: '$<BASE_OBJ_NAME>',
    $<EXTRA_BUILD_ARGS>
  BUILD_PARAMETERS: |-
      parameters {
        $<GIT_BRANCH_BUILD_PARAM>
        $<EXTRA_BUILD_PARAMS>
      }
  GIT_BRANCH_BUILD_PARAM: |-
    stringParam('GIT_BRANCH', '$<GIT_BRANCH>', 'Git branch/tag/hash to build')
  TEST_NAMESPACES_CHOICE_PARAM: |-
    choiceParam('TEST_NAMESPACE', $<TEST_NAMESPACE_CHOICES>, 'Namespace to run tests')

elCicdTemplates:
- templateName: configMap
  objNames: $<BUILD_ARTIFACT_PIPELINES>
  objName: $<PROJECT_ID>-$<>-build-artifact
  mustHaveEveryProfile:
  - nonprod
  - hasArtifacts
  labels: $<MODULE_PIPELINE_LABELS>
  elCicdDefs:
    PIPELINE_DISPLAY_NAME: "BUILD ARTIFACT: $<BASE_OBJ_NAME>"
    PIPELINE_PARAMS: |-
      $<BUILD_PARAMETERS>
    EXTRA_BUILD_PARAMS: |-
        booleanParam('IS_SNAPSHOT', true, 'Is this a snapshot build?')
    EL_CICD_API_METHOD: buildModule
    EL_CICD_API_ARGS: |-
      $<BUILD_MODULE_ARGS>
    AUTH_TOKEN: $<PROJECT_ID>-$<BASE_OBJ_NAME>-git-repo-private-contentkey
  data: $<PROJECT_PIPELINE_CONFIG_MAP_DATA>

- templateName: configMap
  objNames: $<BUILD_COMPONENT_PIPELINES>
  objName: $<PROJECT_ID>-$<>-build-component
  mustHaveEveryProfile:
  - nonprod
  - hasComponents
  labels: $<MODULE_PIPELINE_LABELS>
  elCicdDefs:
    PIPELINE_DISPLAY_NAME: "BUILD COMPONENT: $<BASE_OBJ_NAME>"
    PIPELINE_PARAMS: |-
      $<BUILD_PARAMETERS>
    EXTRA_BUILD_PARAMS: |-
        choiceParam('DEPLOY_TO_NAMESPACE', $<BUILD_NAMESPACE_CHOICES>, 'Namespace to deploy to')
        booleanParam('REINSTALL', false, 'Uninstall $<BASE_OBJ_NAME> before deploying build?')
    EL_CICD_API_METHOD: buildModule
    EL_CICD_API_ARGS: |-
      $<BUILD_MODULE_ARGS>
    EXTRA_BUILD_ARGS: |-
      deployToNamespace: params.DEPLOY_TO_NAMESPACE,
      recreate: params.REINSTALL
    AUTH_TOKEN: $<PROJECT_ID>-$<BASE_OBJ_NAME>-git-repo-private-contentkey
  data: $<PROJECT_PIPELINE_CONFIG_MAP_DATA>

- templateName: configMap
  objNames: $<TEST_COMPONENT_PIPELINES>
  objName: $<PROJECT_ID>-$<>-test-component
  mustHaveEveryProfile:
  - nonprod
  - hasTestComponents
  labels: $<MODULE_PIPELINE_LABELS>
  elCicdDefs:
    PIPELINE_DISPLAY_NAME: "RUN TESTS: $<BASE_OBJ_NAME>"
    PIPELINE_PARAMS: |-
      $<BUILD_PARAMETERS>
    EXTRA_BUILD_PARAMS: |-
        $<TEST_NAMESPACES_CHOICE_PARAM>
    EL_CICD_API_METHOD: runTestModule
    EL_CICD_API_ARGS: |-
      $<BUILD_MODULE_ARGS>
    EXTRA_BUILD_ARGS: |-
      agentNamespace: params.TEST_NAMESPACE
  data: $<PROJECT_PIPELINE_CONFIG_MAP_DATA>

- templateName: configMap
  objNames:
  - build-modules
  - promote-components
  - redeploy-components
  - run-test-components
  - create-release-candidate
  - redeploy-release-candidate
  objName: $<PROJECT_ID>-$<>
  mustHaveEveryProfile:
  - nonprod
  labels: $<SHARED_PROJECT_PIPELINE_LABELS>
  elCicdDefs:
    SHARED_PROJECT_PIPELINE_LABELS:
      teamId: $<TEAM_ID>
      projectid: $<PROJECT_ID>
      jenkins-pipeline: 'true'
      jenkins-shared-pipeline: 'true'
    EL_CICD_API_ARGS: |-
      teamId: '$<TEAM_ID>',
      projectId: '$<PROJECT_ID>',
      $<EXTRA_PIPELINE_ARGS>
  elCicdDefs-build-modules:
    PIPELINE_DISPLAY_NAME: "1. Build Modules"
    EL_CICD_API_METHOD: buildModules
  elCicdDefs-promote-components:
    PIPELINE_DISPLAY_NAME: "2. Promote Components"
    EL_CICD_API_METHOD: promoteComponents
  elCicdDefs-redeploy-components:
    PIPELINE_DISPLAY_NAME: "3. Redeploy Components"
    EL_CICD_API_METHOD: redeployComponents
    PIPELINE_PARAMS: |-
      parameters {
        choiceParam('REDEPLOY_ENVIRONMENT', $<REDEPLOY_ENV_CHOICES>, 'Environment to redeploy')
      }
    EXTRA_PIPELINE_ARGS: "redeployEnv: params.REDEPLOY_ENVIRONMENT"
  elCicdDefs-run-test-components:
    PIPELINE_DISPLAY_NAME: "4.Run Test Components"
    EL_CICD_API_METHOD: redeployComponents
    PIPELINE_PARAMS: |-
      parameters {
        $<TEST_NAMESPACES_CHOICE_PARAM>
      }
    EXTRA_PIPELINE_ARGS: |-
      agentNamespace: params.TEST_NAMESPACE
  elCicdDefs-create-release-candidate:
    PIPELINE_DISPLAY_NAME: "5. Create Release Candidate"
    EL_CICD_API_METHOD: createReleaseCandidate
    PIPELINE_PARAMS: |-
      parameters {
        stringParam('RELEASE_VERSION', null, "$<VERSION_TAG_DESCRIPTION>")
      }
    EXTRA_PIPELINE_ARGS: |-
      releaseVersion: params.RELEASE_VERSION
    VERSION_TAG_DESCRIPTION: 'Release Candidate version tag'
  elCicdDefs-redeploy-release-candidate:
    PIPELINE_DISPLAY_NAME: "6. Redeploy Release Candidate"
    EL_CICD_API_METHOD: redeployReleaseCandidate
    PIPELINE_PARAMS:  |-
      parameters {
        stringParam('RELEASE_VERSION', null, "$<VERSION_TAG_DESCRIPTION>")
      }
    EXTRA_PIPELINE_ARGS: "releaseVersion: params.RELEASE_VERSION"
    VERSION_TAG_DESCRIPTION: "Release candidate version tag to redeploy to the project pre-prod environment"
  data: $<PROJECT_PIPELINE_CONFIG_MAP_DATA>
