elCicdTemplates-common-cicd:
- templateName: secret
  objNames: ${SCM_REPO_SSH_KEY_MODULE_IDS}
  labels:
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  stringData:
    username: "${OBJ_NAME}"
    privateKey: |-
      ${SCM_REPO_SSH_KEY}
