FROM %OCP_IMAGE_REPO%/%FROM_IMAGE%:latest

COPY ["%JENKINS_CONFIGURATION_FILE%", "%JENKINS_PLUGINS_FILE%", "/usr/lib/jenkins/"]

USER root

RUN /usr/local/bin/install-plugins.sh /usr/lib/jenkins/%JENKINS_PLUGINS_FILE%

USER 1001
