elCicdDefs:
  JENKINS: jenkins
  MOUNT_DIR: /mnt/casc-config
  JOBS_DIR: jobs
  JENKINS_RELOAD_URL: ${JENKINS}:8080/reload
  JENKINS_RELOAD_CASC_URL: ${JENKINS}:8080/reload-configuration-as-code/?casc-reload-token=elcicd

elCicdTemplates:
- templateName: job
  objName: ${JENKINS}-pipeline-sync
  image: ${JENKINS_SYNC_JOB_IMAGE}
  imagePullSecret: el-cicd-${JENKINS}-pull-secret
  projectedVolumeLabels:
  - name: mounted-${JENKINS}-${JOBS_DIR}
    mountPath: ${MOUNT_DIR}
    labels:
    - ${JENKINS}-folder
    - ${JENKINS}-pipeline
    - ${JENKINS}-casc
  serviceAccountName: ${JENKINS}
  command: ["/bin/bash"]
  args:
  - -c
  - pwd;
    id;
    set -x ;
    mkdir ${JOBS_DIR};
    cp ${MOUNT_DIR}/*.yaml ${JOBS_DIR};
    chmod 777 -R ${JOBS_DIR};
    cd ${JOBS_DIR};
    echo "Syncing Jenkins pipelines";
    JENKINS_POD=$(oc get pods -l name=${JENKINS} --no-headers -o custom-columns=:.metadata.name);
    oc exec -i $JENKINS_POD -- find /var/lib/${JENKINS}/${JOBS_DIR} -name config.xml -exec rm -vf {} \; ;
    oc exec -i $JENKINS_POD -- find ${JENKINS_CONFIG_FILE_PATH} -name \*.yaml -exec rm -vf {} \; ;
    tar cf - . | kubectl exec -i  $JENKINS_POD -- tar xf - -C ${JENKINS_CONFIG_FILE_PATH};
    echo -n "HTTP CODE FROM JENKINS RESTART -> ";
    curl -ksSL -o /dev/null --fail-with-body -X POST -w '%{http_code}\n' -H "Authorization:Bearer $(oc whoami -t)" ${JENKINS_RELOAD_URL} ;
    curl -ksSL -o /dev/null --fail-with-body -X POST -w '%{http_code}\n' -H "Authorization:Bearer $(oc whoami -t)" ${JENKINS_RELOAD_CASC_URL} ;
    echo "el-CICD Jenkins ${JOBS_DIR} updated";