#!/usr/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later

RESOURCES_DIR=${BOOTSTRAP_DIR}/resources
BUILD_CONFIGS_DIR=${RESOURCES_DIR}/buildconfigs
TEMPLATES_DIR=${RESOURCES_DIR}/templates

CONFIG_REPOSITORY=${BOOTSTRAP_DIR}/../el-CICD-config
CONFIG_REPOSITORY_BOOTSTRAP=${CONFIG_REPOSITORY}/bootstrap
CONFIG_REPOSITORY_AGENTS=${CONFIG_REPOSITORY}/agents

SECRET_FILE_DIR=${BOOTSTRAP_DIR}/../cicd-secrets
SECRET_FILE_TEMP_DIR=${SECRET_FILE_DIR}/tmp

source ${CONFIG_REPOSITORY}/el-cicd-bootstrap.config
source ${CONFIG_REPOSITORY}/el-cicd-secrets.config