{{- $_ := set $.Values "UNDEFINED" "undefined" -}}

{{/*
Kustomization YAML
*/}}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
{{- if $.Values.componentKustDir }}
- {{ $.Values.componentKustDir }}
{{- end }}

namespace: "{{ .Release.Namespace }}"

commonLabels:
  teamid: "{{ $.Values.teamId }}"
  projectid: "{{ $.Values.projectId }}"
  component: "{{ .Release.Name }}"

labels:
- pairs:
    scm-repo: "{{ $.Values.scmRepoName }}"
    deployment-branch: "{{ $.Values.deploymentBranch }}"
    src-commit-hash: "{{ $.Values.srcCommitHash }}"
    release-version: "{{ $.Values.releaseVersionTag  | default $.Values.UNDEFINED }}"
    code-base: "{{ $.Values.codeBase }}"
  includeTemplates: true

configMapGenerator:
- name: {{ $.Values.projectId }}-{{ $.Values.component }}-{{ $.Values.metaInfoPostfix }}
  options:
    disableNameSuffixHash: true
  literals:
  - projectid="{{ $.Values.projectId }}"
  - component="{{ .Release.Name }}"
  - profiles="{{ join "," $.Values.profiles }}"
  - scm-repo="{{ $.Values.scmRepoName }}"
  - src-commit-hash="{{ $.Values.srcCommitHash }}"
  - deployment-branch="{{ $.Values.deploymentBranch | default $.Values.UNDEFINED }}"
  - release-version="{{ $.Values.releaseVersionTag  | default $.Values.UNDEFINED }}"
  - code-base="{{ $.Values.codeBase }}"
  - build-number="{{ $.Values.buildNumber }}"
  - deploy-time="{{ now | date "2006-01-02-15:04:05" }}"

