apiVersion: v1
type: postrenderer/v1
name: onboarding-plugin
version: 0.1.0
runtime: subprocess
runtimeConfig:
  platformCommand:
  - command: ${HELM_PLUGIN_DIR}/onboarding-plugin/onboarding-post-renderer.sh